blueprint:
  name: Color Breathing Effect
  description: Smoothly cycles brightness and color on a group of lights.
  domain: script
  input:
    light_targets:
      name: Light Entities
      description: The lights to apply the breathing effect to
      selector:
        entity:
          domain: light
          multiple: true

    cycle_speed:
      name: Speed (seconds)
      description: Time for one up/down fade + color shift
      default: 6
      selector:
        number:
          min: 2
          max: 30
          unit_of_measurement: seconds
          step: 1

    brightness_low:
      name: Minimum Brightness
      default: 50
      selector:
        number:
          min: 1
          max: 254
          step: 1

    brightness_high:
      name: Maximum Brightness
      default: 254
      selector:
        number:
          min: 1
          max: 254
          step: 1

mode: restart
sequence:
  - repeat:
      while:
        - condition: template
          value_template: true
      sequence:
        - variables:
            cycle_speed_val: !input cycle_speed
            brightness_high_val: !input brightness_high
            brightness_low_val: !input brightness_low
            transition_val: "{{ (cycle_speed_val / 2) | int }}_
